name: gym_guard_app
description: "GymGuard - AI Workout Assistant"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ðŸ” Security & Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2

  # ðŸ†” Unique IDs (fÃ¼r mehrere gleiche Namen)
  uuid: ^4.3.3

  # ðŸ“· Camera & AI
  camera: ^0.10.5+9
  google_mlkit_pose_detection: ^0.12.0
  vector_math: ^2.1.4
  permission_handler: ^11.3.0


  # ðŸ”Š Voice & Utils
  flutter_tts: ^3.8.3
  intl: ^0.19.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
